CREATE TYPE ContactType AS ENUM ('FREELANCER','EMPLOYEE');
CREATE TABLE CONTACT(
ID INT PRIMARY KEY NOT NULL,
FIRSTNAME VARCHAR,
LASTNAME VARCHAR,
ADRESSE VARCHAR,
TYPE ContactType,
TVA NUMBER
);
CREATE TABLE COMPANY(
ID INT PRIMARY KEY NOT NULL,
ADRESSE VARCHAR,
TVA NUMBER
);
CREATE SEQUENCE contact_sequence;
CREATE SEQUENCE company_sequence;
CREATE TABLE CONTACT_COMPANY(
CONTACT_ID INT NOT NULL,
COMPANY_ID INT NOT NULL,
PRIMARY KEY(CONTACT_ID, COMPANY_ID)
);